### ISSUE TITLE
failed to start v2ray-core: geoip.dat or geosite.dat file does not exists

### ISSUE THREAD

**Issue by 725216** [ningmoon/v2ray#1]
用不了？报错
failed to start v2ray-core: geoip.dat or geosite.dat file does not exists

**Comment by 725216** [comment]
按别的教程装了几个dat文件好了，问题是怎么删除失效的服务器？

**Comment by yongyuan-chen** [comment]
failed to start v2ray-core: geoip.dat or geosite.dat file does not exists #1  请问这个问题哪里可以解决

**Comment by yongyuan-chen** [comment]
@725216 求助，怎么解决的阿
