### ISSUE TITLE
检测到 geosite.dat, geoip.dat 文件或 v2ray-core 可能未正确安装，请检查

### ISSUE THREAD

**Issue by xufromxu** [ningmoon/v2ray#2]
检测到 geosite.dat, geoip.dat 文件或 v2ray-core 可能未正确安装，请检查

**Comment by yongyuan-chen** [comment]
@xufromxu  求助，怎么解决的阿

**Comment by SenyFish** [comment]
这作者复制都复制不对，安装命令是错的，这两年了还没人发现吗

**Comment by keigen1017** [comment]
> 这作者复制都复制不对，安装命令是错的，这两年了还没人发现吗

那仁兄也指出个对的方案啊，你说风凉话有什么用啊

**Comment by ginitaimeiyty** [comment]
发了兄弟。。。一直没人看我就给删了，这作者把`sudo apt install v2raya`这条命令弄错了,改成：
```
sudo apt install v2raya v2ray
```
就好了，就这么简单。。。

**Comment by SenyFish** [comment]
> > 这作者复制都复制不对，安装命令是错的，这两年了还没人发现吗
> 
> 那仁兄也指出个对的方案啊，你说风凉话有什么用啊

发了兄弟。。。一直没人看我就给删了，这作者把`sudo apt install v2raya`这条命令弄错了,改成：
```
sudo apt install v2raya v2ray
```
就好了，就这么简单。。。

**Comment by xiongsanming** [comment]
> > > 这作者复制都复制不对，安装命令是错的，这两年了还没人发现吗
> > 
> > 
> > 那仁兄也指出个对的方案啊，你说风凉话有什么用啊
> 
> 发了兄弟。。。一直没人看我就给删了，这作者把`sudo apt install v2raya`这条命令弄错了,改成：
> 
> ```
> sudo apt install v2raya v2ray
> ```
> 
> 就好了，就这么简单。。。

为什么显示running，然后ping可以ping通但是http连不通

**Comment by prohommunel** [comment]
> > > > 这作者复制都复制不对，安装命令是错的，这两年了还没人发现吗
> > > 
> > > 
> > > 那仁兄也指出个对的方案啊，你说风凉话有什么用啊
> > 
> > 
> > 发了兄弟。。。一直没人看我就给删了，这作者把`sudo apt install v2raya`这条命令弄错了,改成：
> > ```
> > sudo apt install v2raya v2ray
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 就好了，就这么简单。。。
> 
> 为什么显示running，然后ping可以ping通但是http连不通

我sb了，纯订阅的问题，有的订阅必须得用clash verge
